spring:
  application:
    name: dgdr-server
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080
  public-url: https://your-ngrok.io
  agent-phone: 821012345678

clova:
  speech:
    invoke-url: clovaspeech-gw.ncloud.com:50051
    secret-key: 25639c442fa44150a055a44b6671199a
    grpc:
      host: clovaspeech-gw.ncloud.com
      port: 50051

vonage:
  apiKey: 실제값
  apiSecret: 실제값
  applicationId: 실제값
  privateKeyPath: ./private.key

aws:
  access-key: AKIA...
  secret-key: xxxxx
  region: ap-northeast-2
  sagemaker:
    endpoint-name: 실제엔드포인트

jwt:
  secret: s2i3g4n5a6l7s8e9c0r3e2t1xs12881sllsd888xcvu9z821lk4dxc88z8ds3123
  accessToken:
    expiration: 3600
  refreshToken:
    expiration: 86400